# Generated by Django 5.2 on 2025-05-02 15:39

import silant.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_date', models.DateField(verbose_name='Дата отказа')),
                ('operating_hours', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('failure_description', models.TextField(verbose_name='Описание отказа')),
                ('spare_parts', models.TextField(blank=True, verbose_name='Используемые запасные части')),
                ('recovery_date', models.DateField(verbose_name='Дата восстановления')),
                ('downtime', models.PositiveIntegerField(editable=False, verbose_name='Время простоя техники (дни)')),
            ],
            options={
                'verbose_name': 'Рекламация',
                'verbose_name_plural': 'Рекламации',
            },
            bases=(silant.models.AccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Machine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('machine_serial', models.CharField(max_length=50, unique=True, verbose_name='Зав. № машины')),
                ('engine_serial', models.CharField(max_length=50, verbose_name='Зав. № двигателя')),
                ('transmission_serial', models.CharField(max_length=50, verbose_name='Зав. № трансмиссии')),
                ('drive_axle_serial', models.CharField(max_length=50, verbose_name='Зав. № ведущего моста')),
                ('steering_axle_serial', models.CharField(max_length=50, verbose_name='Зав. № управляемого моста')),
                ('supply_contract', models.CharField(max_length=100, verbose_name='Договор поставки №, дата')),
                ('shipping_date', models.DateField(verbose_name='Дата отгрузки с завода')),
                ('consignee', models.CharField(max_length=200, verbose_name='Грузополучатель')),
                ('delivery_address', models.CharField(max_length=200, verbose_name='Адрес поставки')),
                ('equipment', models.TextField(verbose_name='Комплектация (доп. опции)')),
            ],
            options={
                'verbose_name': 'Машина',
                'verbose_name_plural': 'Машины',
            },
            bases=(silant.models.AccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Maintenance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maintenance_date', models.DateField(verbose_name='Дата проведения ТО')),
                ('operating_hours', models.PositiveIntegerField(verbose_name='Наработка, м/час')),
                ('work_order', models.CharField(max_length=50, verbose_name='№ заказ-наряда')),
                ('work_order_date', models.DateField(verbose_name='Дата заказ-наряда')),
            ],
            options={
                'verbose_name': 'Техническое обслуживание',
                'verbose_name_plural': 'Технические обслуживания',
            },
            bases=(silant.models.AccessMixin, models.Model),
        ),
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название справочника')),
                ('title', models.CharField(max_length=100, verbose_name='Название элемента')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Справочник',
                'verbose_name_plural': 'Справочники',
            },
            bases=(silant.models.AccessMixin, models.Model),
        ),
    ]
