# Generated by Django 5.2 on 2025-05-02 15:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('silant', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='complaints', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='machine',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machines', to=settings.AUTH_USER_MODEL, verbose_name='Клиент'),
        ),
        migrations.AddField(
            model_name='machine',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='serviced_machines', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='complaints', to='silant.machine', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='machine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenances', to='silant.machine', verbose_name='Машина'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='service_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_orders', to=settings.AUTH_USER_MODEL, verbose_name='Сервисная компания'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_companies', to='silant.reference', verbose_name='Организация, проводившая ТО'),
        ),
        migrations.AddField(
            model_name='maintenance',
            name='maintenance_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='maintenance_types', to='silant.reference', verbose_name='Вид ТО'),
        ),
        migrations.AddField(
            model_name='machine',
            name='drive_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='drive_axle_models', to='silant.reference', verbose_name='Модель ведущего моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='engine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='engine_models', to='silant.reference', verbose_name='Модель двигателя'),
        ),
        migrations.AddField(
            model_name='machine',
            name='machine_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='machine_models', to='silant.reference', verbose_name='Модель техники'),
        ),
        migrations.AddField(
            model_name='machine',
            name='steering_axle_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='steering_axle_models', to='silant.reference', verbose_name='Модель управляемого моста'),
        ),
        migrations.AddField(
            model_name='machine',
            name='transmission_model',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='transmission_models', to='silant.reference', verbose_name='Модель трансмиссии'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='failure_node',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='failure_nodes', to='silant.reference', verbose_name='Узел отказа'),
        ),
        migrations.AddField(
            model_name='complaint',
            name='recovery_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recovery_methods', to='silant.reference', verbose_name='Способ восстановления'),
        ),
    ]
